node {
    def mvnHome
    try {
         stage('sceptre') { //(1)
            sh "sceptre --help"
        }
        stage('Checkout') { //(1)
            git branch: 'papu', credentialsId: '0957eb3e-b490-4d0a-b06e-c993ec94a732', url: 'https://bitbucket.org/synectiks/cloudautomationexamples.git'
            mvnHome = tool 'maven3'
        }
        stage('Build') { //(2)
            dir('jenkin/services/service-1') {
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
            }
        }
        stage('Tests') { //(3)
            junit '**/target/surefire-reports/TEST-*.xml'
            archive 'target/*.jar'
            step([$class: 'JacocoPublisher', execPattern: '**/target/jacoco.exec'])
        }
        stage('Report') { //(4)
            if (currentBuild.currentResult == 'UNSTABLE') {
                currentBuild.result = "UNSTABLE"
            } else {
                currentBuild.result = "SUCCESS"
            }
            step([$class: 'InfluxDbPublisher', customData: null, customDataMap: null, customPrefix: null, target: 'grafana'])
        }
    } catch (Exception e) {
        currentBuild.result = "FAILURE"
        step([$class: 'InfluxDbPublisher', customData: null, customDataMap: null, customPrefix: null, target: 'grafana'])
    }
}