pipeline {
    options
    {
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }
    agent any
    environment { 
        VERSION = 'latest'
    }
    stages {
        stage('WSClean') {
            steps { 
                step([$class:'WsCleanup'])
            }
        } 
        stage('Checkout') {
            steps { 
                script {
                    try {
                        git url: 'https://github.com/xformation/examples.git'
                    } catch (Exception e) {
                        currentBuild.result = "FAILURE"
                        step([$class: 'InfluxDbPublisher', customData: null, customDataMap: null, customPrefix: null, target: 'grafana'])
                    }
                }
            }
        }         
        stage('CreateBuckets') {
            parallel {
                stage('DevBucket') {
                    steps {
                        script {
                            try {
                                if(isDev == 'true') {
                                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'synectiks-dev']]) {                                    
                                        sh "sceptre --dir wordpress launch-env dev"
                                    }
                                }
                            } catch (Exception e) {
                                currentBuild.result = "FAILURE"
                                step([$class: 'InfluxDbPublisher', customData: null, customDataMap: null, customPrefix: null, target: 'grafana'])
                                throw e
                            }
                        }
                    }
                }
                stage('TestBucket') {
                    steps {
                        script {
                            try {
                                if (isTest == 'true') {
                                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'synectiks-test']]) {                                   
                                        sh "sceptre --dir wordpress launch-env test"
                                    }                                   
                                }
                            } catch (Exception e) {
                                currentBuild.result = "FAILURE"
                                step([$class: 'InfluxDbPublisher', customData: null, customDataMap: null, customPrefix: null, target: 'grafana'])
                                throw e
                            }
                        }
                    }
                }
                stage('StageBucket') {
                    steps {
                        script {
                            try {
                                if (isStage == 'true') {
                                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'synectiks-stage']]) {                                    
                                        sh "sceptre --dir wordpress launch-env stage"
                                    }
                                }
                            } catch (Exception e) {
                                currentBuild.result = "FAILURE"
                                step([$class: 'InfluxDbPublisher', customData: null, customDataMap: null, customPrefix: null, target: 'grafana'])
                                throw e
                            }
                        }
                    }
                }
                stage('ProdBucket') {
                    steps {
                        script {
                            try {
                                if(isProd == 'true') {
                                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'synectiks-prod']]) {
                                        sh "sceptre --dir wordpress launch-env prod"
                                    }
                                }
                            } catch (Exception e) {
                                currentBuild.result = "FAILURE"
                                step([$class: 'InfluxDbPublisher', customData: null, customDataMap: null, customPrefix: null, target: 'grafana'])
                                throw e
                            }
                        }
                    }
                }
            }
        }
    } 
    post
    {
        always
        {
            // make sure 
            echo "doing some post processing"
        }
    }
}