template_path: templates/ecs-cluster.json
parameters:
  ProductName: !stack_output backbone::ProductName
  EnvironmentName: !stack_output backbone::EnvironmentName
  VPC:  !stack_output backbone::VPC
  PrivateSubnets: !stack_output backbone::PrivateSubnets
  FileSystem: !stack_output efs::FileSystem
  SshSecurityGroup: !stack_output security-groups::SshSecurityGroup
  ClusterSecurityGroup: !stack_output security-groups::ClusterSecurityGroup
  EcsHostSecurityGroup: !stack_output security-groups::EcsHostSecurityGroup
  EfsSecurityGroup:  !stack_output efs::EfsAccessSecurityGroup
  AddEfs: "true"