version: "3.2"
services:
  jira:
    build: jira
    ports:
      - "8080:8080"
    volumes:
    - type: volume
      source: /opt/data/composehome/jirahome
      target: /opt/jira-home
    links:
    - database
  sonar:
    image: sonarqube:alpine
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
    - type: volume
      source: /opt/data/composehome/sonardata
      target: /opt/sonarcube/data
    environment:
      - SONARCUBE_JDBC_USERNAME=sonar
      - SONARCUBE_JDBC_PASSWORD=sonar
      - SONARCUBE_JDBC_URL=jdbc:postgresql://database/sonar
    links:
    - database
  database:
    image: postgres:9.4
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
      - type: volume
        source:  ./jira/scripts
        target: /docker-entrypoint-initdb.d/
      - type: volume
        source: ./jira/dump
        target: /tmp
  mysql:
    image: mysql:5.7
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    restart: always
  jenkins:
    build: jenkin
    ports:
      - "38080:8080"
      - "5000:5000"
    restart: "always"
    volumes:
      - type: volume
        source: /opt/data/composehome/jenkinhome
        target: /var/jenkins_home
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: "always"
    volumes:
      - type: volume
        source: /opt/data/composehome/grafanadata
        target: /var/lib/grafana
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    restart: "always"
    volumes:
      - type: volume
        source: /opt/data/composehome/influxdata
        target: /var/lib/influxdb
volumes:
  dbdata:
  mysqldata:
