template_path: templates/mainservice.json
parameters:
  ProductName: !stack_output backbone::ProductName
  EnvironmentName: !stack_output backbone::EnvironmentName
  VPC:  !stack_output backbone::VPC
  Cluster: !stack_output ecscluster::Cluster
  Listener: !stack_output loadbalancer::Listener
  LoadbalancerUrl:  !stack_output loadbalancer::LoadBalancerUrl
  DBHost:  !stack_output rds::MasterHosturl
  DBUser: root
  DBPassword: password
  UploadDir: /opt/data