template_path: src/wordpress.py

parameters:
  VpcId: !stack_output vpc::VpcId 
  Environment: !stack_output vpc::Environment 
  Subnet1: !stack_output vpc::PublicSubnet1ID
  Subnet2: !stack_output vpc::PublicSubnet2ID  
  RDSEndpoint: !stack_output rds::MySQLAddress
  FileSystemID: !stack_output efs::FileSystemID
  ElbSecurityGroup: !stack_output security-groups::ELBsg 
  WebSecurityGroup: !stack_output security-groups::WEBsg
  AvailabilityZone1: us-east-1a
  AvailabilityZone2: us-east-1b      
  Hostname: www-prod
  Domain: synectiks.net
  KeyName: mykey
  InstanceType: t2.large
  DBName: !stack_output rds::DBName
  DBPass: wordpress123
  DBUser: !stack_output rds::DBUser
  WebServerCapacity: "4"

